- hosts: '{{inventory}}'
  tasks:
  - name: Get Disk Space
    shell: "df -h"
    register: pid

  - debug: var=pid.stdout_lines

  - name: Get Process
    shell: "ps -a"
    register: ps

  - debug: var=ps.stdout_lines